version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - coturn

  postgres:
    image: postgres:15
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    environment:
      - TURN_USERNAME=${TURN_USERNAME:-turn}
      - TURN_PASSWORD=${TURN_PASSWORD:-turn}
      - ./turnserver.conf:/etc/coturn/turnserver.conf

volumes:
  postgres_data:
  redis_data: 